"""add role to users

Revision ID: dc07c8c32617
Revises: 3c4e8627b7c5
Create Date: 2026-08-20 16:23:56.067264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc07c8c32617'
down_revision: Union[str, Sequence[str], None] = '3c4e8627b7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(),
            nullable=False,
            server_default='user'
        )
    )

    op.alter_column(
        'users',
        'role',
        server_default=None
    )

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
